networks:
  elk-network:
    external: true
services:
  elasticsearch:
    image: elasticsearch:8.14.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:8.14.1
    ports:
      - 5601:5601
    networks:
      - elk-network
  logstash:
    image: logstash:8.14.1
    networks:
      - elk-network
